#!/bin/sh
nm-applet &
xautolock -time 10 -locker slock &
xfce4-power-manager &
/usr/lib/notification-daemon/notification-daemon &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
blueberry-tray &
