#!/bin/sh
nm-applet &
xautolock -time 10 -locker slock &
xfce4-power-manager &
/usr/lib/notification-daemon-1.0/notification-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
blueberry-tray &
